import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PayUp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container">
        {/* <div className="w-screen h-[50px] bg-red-300">
          <h1>header</h1>
        </div>
        <div className="flex flex-row">
          <div className="w-2/12">
            <h1>Left</h1>
          </div>
          <div className="w-10/12 bg-slate-500 h-screen">{children}</div>
        </div> */}
        {children}
      </body>
    </html>
  );
}
